### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by Satont**
Notable changes:

1. On each commit `prettier` will be runned before actuall commit.
   That means, there will be always formatted code.
   Commits: https://github.com/LWJerri/Riddea/pull/18/commits/a5a33635dc4c8a0d052a8dbe274cb3f9569f0d05, https://github.com/LWJerri/Riddea/pull/18/commits/156be5f3437b3632e2a69c5d95454db32f5bed0d
2. `package.json` not builded into `dist` directory. Instead of it application will read file on start. https://github.com/LWJerri/Riddea/pull/18/commits/ad3e55e95b87692760b375425fa3c93d663618fd 
3. Whole working with db was refactored. Your way was wrong. You should use single connection for application, not create connection on each functions calls.
3.1. Also i changed `findOne() -> count + 1 -> update()` way to just `.increment()` https://github.com/LWJerri/Riddea/pull/18/commits/fb0f56aef884945807ec97f1d8382cf0d9affc9a
4. Added and refactored npm commands (https://github.com/LWJerri/Riddea/pull/18/commits/33f3890b5559281ef64d314c2d531ebdbbd200cd):
4.1 `npm run prettier` — will manually run prettier for `src` directory
4.2 `npm run build` — first delete `dist` directory, then build
4.3 `npm run start` — simplified code to just `"start": "node ./dist/src/app.js",`. Running of migration was moved to `"prestart": "npm run migration:run",`

### CODE REVIEW

**Comment by Satont** [comment]
You do not need squash my PR, i guess. But really doesn't metter.

**Review by LWJerri — COMMENTED** [review]
Viewed code changes.

**Review by LWJerri — COMMENTED** [review]
Looked at the latest code changes.

**Review by LWJerri — COMMENTED** [review]
Good idea with autoloading commands description in bot.

**Comment by LWJerri** [comment]
I made little changes in callback files (#18).

**Comment by LWJerri** [comment]
Hello! I'm grateful for your help, you showed my main problem with the correct work database and make my code cleared from bad lines. Very big thanks to you, @Satont!

**Pull request merged**
